### ISSUE TITLE
Font variants (weights, shapes) don't work

### ISSUE THREAD

**Issue by mg-13** [silkeh/latex-sourceserifpro#1]
Using the package sourceserifpro, `\emph` or `\textit` are not working for me.
Quoting from the [readme file](http://www.adobe.com/products/type/font-information/source-serif-pro-readme.html) by adobe:

> One should not, however, select a base font which has no style-linked variant, and then use the bold or italic styling button. Doing so will either have no effect, or result in programmatic bolding or slanting of the base font, which will usually produce inferior screen and print results.

The readme file also states that there are no extra 'fonts' for every variant but each represents a set which includes an italic variant that _should_ work.

Also, the options _light_, _extralight_, _bold_, _semibold_ and _black_ are not working. The weight is always the same.

Both of the problems are not existent for [`sourcesanspro`](https://github.com/silkeh/latex-sourcesanspro), which should be similar, I guess

**Comment by silkeh** [comment]
I've fixed the weight issues. They were caused by a missing implementation for the type 1 fonts. Please test if they are working for you in the latest master.
The lack of italics I cannot fix because they aren't implemented (see the table in the readme by Adobe).

**Comment by mg-13** [comment]
Thanks, the weight fix LGTM
Sorry, I misinterpreted when I was able to set the font italic in my browser. Seems like it just got tilted over (I'm not that into fonts).They even have an open [issue](https://github.com/adobe-fonts/source-serif-pro/issues/2) for the missing italics

**Comment by ShikiSuen** [comment]
Please use Fourier package in lieu of Source Serif Pro until italics are available in the latter.
