### ISSUE TITLE
Missing small caps

### ISSUE THREAD

**Issue by jrmiller82** [silkeh/latex-sourceserifpro#2]
Hi! Thanks for your work getting this into latex; however, neither the T1 nor the OTF font have their italics or small caps (unlike your sourcesanspro package). Can you look into adding please? Perhaps the font didn't have them when you last looked at it, but adobe has now added those features.

**Comment by silkeh** [comment]
Hi, thanks for your issue.
At the moment Source Serif Pro does not have italics (see #3). Small caps [were added recently](https://github.com/adobe-fonts/source-serif-pro/releases/tag/2.000R), and I will update the package soon.

**Comment by jrmiller82** [comment]
Gotcha. Had no idea the italics were missing in upstream. My apologies. Thanks again for packaging for LaTeX.

**Comment by silkeh** [comment]
Version 1.3 is out and includes italics and small caps, download here: https://github.com/silkeh/latex-sourceserifpro/releases/tag/v1.3
