### ISSUE TITLE
Missing italics

### ISSUE THREAD

**Issue by silkeh** [silkeh/latex-sourceserifpro#3]
As noted in #1 and #2, there are no italics as of yet. Track adobe-fonts/source-serif-pro#2 for progress.

**Comment by jrmiller82** [comment]
Thanks again for your work packaging this and for keeping up with adobe.

**Comment by pela9** [comment]
Italics for sourceserifpro has finally arrived! It would be great with a new version of the LaTeX package.

**Comment by silkeh** [comment]
Version 1.3 is out and includes italics, download here: https://github.com/silkeh/latex-sourceserifpro/releases/tag/v1.3 (feedback is appreciated)

@pela9 thanks for the heads up!
